version: '3'

services:
  linux:
    image: ghcr.io/densuke-st/linux-vm-docker:v3
    privileged: true
    ports:
      - 2022:22
      - 8080:80
      - 3306:3306
    volumes:
      - ubuntu-home:/home

volumes:
  ubuntu-home:
    external: true
