name: Docker Image CI

on:
  push:
    branches: [ "ci", "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  build_job:
    name: Build on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build -t densukest/ubuntu-it-soft:v1 --build-arg PASSWORD=penguin src
    - name: export image
      run: |
        mkdir dist
        docker image save densukest/ubuntu-it-soft:v1 | gzip > dist/test.tar.gz
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: image-${{ matrix.runner }}
        path: dist/*
  test:
    needs: build_job
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, self-hosted]
    steps:
    - name: download image
      uses: actions/download-artifact@v3
      with:
        name: image-${{ matrix.runner }}
        path: dist
    - name: import image
      run: |
        find dist -ls
        docker image load --input dist/test.tar.gz
    - name: Test connection
      run: |
        docker run -P --name test -d --privileged  densukest/ubuntu-it-soft:v1
        SSHPORT=$(docker container ps test | egrep -o '0.0.0.0:[0-9]+->22/tcp' | sed -r -e 's;.*:([0-9]+)->.*;\1;')
        sudo apt-get update; sudo apt-get install -y sshpass
        sshpass -p penguin ssh -p ${SSHPORT} -o StrictHostKeyChecking=false linux@127.0.0.1 uname -a
  deploy:
    needs: test
    if: ${{ endsWith(github.ref, '/main') && github.event_name != 'pull_request' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, self-hosted]
    steps:
      - name: download image
        uses: actions/download-artifact@v3
        with:
          name: image-${{ matrix.arch }}
          path: dist
      - name: import image
        run: |
          find dist -ls
          docker image load --input dist/test.tar.gz
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH }}
      - name: upload image
        run: |
          docker push densukest/ubuntu-it-soft:v1
