name: Docker Image CI(main)

on:
  push:
    branches: [ "ci", "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    #runs-on: self-hosted
    # env:
    #   TESTIMAGE: test-${{ github.run_id }}-${{ github.run_number }}
    steps:
    - uses: actions/checkout@v3
    - name: Set random image name
      run: |
        echo "TESTIMAGE=testimage-${RANDOM}:${RANDOM}" > $GITHUB_ENV
        echo "NAME=test-${RANDOM}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        BUILD_ARG="--build-arg PASSWORD=penguin"
        grep -q '/main$' <<< "${{ github.ref }}" && BUILD_ARG="${BUILD_ARG} --no-cache"
        docker buildx create --use --name builder
        docker buildx build --load -t ${TESTIMAGE} ${BUILD_ARG}  src
    - name: Test connection
      run: |
        #NAME="test-${RANDOM}"
        docker run -P --name "${NAME}" -d --rm --privileged  ${TESTIMAGE}
        SSHPORT=$(docker container ps -f "name=${NAME}" | egrep -o '0.0.0.0:[0-9]+->22/tcp' | sed -r -e 's;.*:([0-9]+)->.*;\1;')
        echo "SSHPORT=${SSHPORT}" >> $GITHUB_ENV
        sudo apt-get update; sudo apt-get install -y sshpass
        sshpass -p penguin ssh -p ${SSHPORT} -o StrictHostKeyChecking=false linux@127.0.0.1 uname -a
        # test for localed time
        sshpass -p penguin ssh -p ${SSHPORT} -o StrictHostKeyChecking=false linux@127.0.0.1 \
          bash -ec "test -f /etc/profile.d/locale-ja.sh; source /etc/profile.d/locale-ja.sh; date" | egrep '年'
    - name: Test /etc/crontab
      run: |
        sshpass -p penguin ssh -p ${SSHPORT} -o StrictHostKeyChecking=false linux@127.0.0.1 \
        test -f /etc/crontab
    - name: Stop the container
      run: docker stop ${NAME}
    #- name: Test skr
    #  run: |
    #      docker run --rm ${TESTIMAGE} sh -c 'test -x /usr/local/bin/skr'
    - name: Log in to the Container registry
      #if: ${{ endsWith(github.ref, '/main') && github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      #if: ${{ endsWith(github.ref, '/main') && github.event_name != 'pull_request' }}
      uses: docker/metadata-action@v4
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # latestタグも追加
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
    - name: Set up Docker Buildx
      #if: ${{ endsWith(github.ref, '/main') && github.event_name != 'pull_request' }}
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      #if: ${{ endsWith(github.ref, '/main') && github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v4
      with:
        context: src
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PASSWORD=penguin
        platforms: linux/amd64
        #platforms: linux/amd64,linux/arm64
        provenance: false
    - name: cleanup image
      run: docker image rm ${TESTIMAGE}
