name: Docker Image CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}
    strategy:
      matrix:
        include:
        - arch: amd64
          distro: ubuntu-latest
        - arch: aarch64
          distro: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_AUTH }}
    - name: Build the Docker image
      run: |
        docker build -t densukest/ubuntu-it-soft:v1 --build-arg PASSWORD=penguin src
    - name: Test connection
      run: |
        docker run -p 2022:22 --name test -d --privileged  densukest/ubuntu-it-soft:v1
        bash -xe ./test/conn
    - name: Remove test container
      run: |
        docker stop test
        docker rm test
    - name: Push image
      run: |
        docker push densukest/ubuntu-it-soft:v1
