name: Docker Image CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}
    strategy:
      matrix:
        include:
        - arch: amd64
          distro: ubuntu-latest
        - arch: aarch64
          distro: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_AUTH }}
    - name: Build the Docker image
      run: |
        docker buildx create --use --name mybuilder
        docker buildx build -t densukest/ubuntu-it-soft:v1 --platform=linux/amd64,linux/arm64 --push src
