name: Docker Image CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}
    strategy:
      matrix:
        include:
        - arch: amd64
          distro: ubuntu-latest
        - arch: aarch64
          distro: ubuntu-latest
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
    - uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_AUTH }}
    - name: Build the Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build -t densukest/ubuntu-it-soft:v1 --build-arg PASSWORD=penguin src
    - name: export image
      run: |
        mkdir dist
        docker image save | gzip > dist/test.tar.gz
    - name: upload artifact
      uses: actions/upload-artifacts@v3
      with:
        name: image-${{ matrix.arch }}
        path: dist/*
    - name: import image
      uses: actions/download-artifacts@v3
      with:
        name: image-${{ matrix.arch }}
        path: dist
    - name: check
      run: |
        find dist
    - name: Test connection
      run: |
        docker run -p 2022:22 --name test -d --privileged  densukest/ubuntu-it-soft:v1
        sudo apt-get update; sudo apt-get install -y sshpass
        sshpass -p penguin ssh -p 2022 -o StrictHostKeyChecking=false linux@127.0.0.1 uname -a
