name: Docker Image CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_AUTH }}
    - name: Build the Docker image
      run: |
        docker buildx create --use mybuilder
        docker buildx build -t densukest/ubuntu-it-soft:v1 --push src
