name: Docker Image CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.DOCKER_AUTH }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username densuke-st --password "${{ secrets.DOCKER_AUTH }}" 
        docker buildx create --use mybuilder
        docker builxd build -t densukest/ubuntu-it-soft:v1 --push src
