name: リリース工程(main,latestタグ)

on:
  workflow_run:
    workflows: ["イメージ生成ができるかのCI"]
    types:
      - completed
    branches:
      - "main"
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
  # 毎週日曜日の日本時間の午前3時に実行する
  schedule:
    - cron: '0 18 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ビルド作業
      uses: densuke/image-build@v1.0.1
      with:
        REGISTRY: ${{ env.REGISTRY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        REPO_USER: ${{ secrets.REPO_USER }}
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        TAGS: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
